### ISSUE TITLE
Wiki Access

### ISSUE THREAD

**Issue by oschrenk** [lingeringsocket/jgrapht#2]
Wouldn't it be good to open up wiki access for this project?

I wanted to integrarte[wiki.jgrapht.org](http://wiki.jgrapht.org) into it but had two problems. Neither the old or the new wiki is accesible,

**Comment by jsichi** [comment]
Bleh...I have migrated the wiki too many times already, but yeah, it would be good to do it one more time.  For now, it lives here:

http://sourceforge.net/apps/mediawiki/jgrapht/index.php?title=Main_Page

I need to move the jgrapht.org domain and then fix the wiki.jgrapht.org DNS.

**Comment by oschrenk** [comment]
I can do it over the weekend.

I propose the following changes:
- remove news section, The commit history, HISTORY.md and announcement on mailing list should suffice
- pull etc/graph-links.html into wiki, remove from source repo
- pull etc/release-process.html into wiki, remove from source repo (merge with existing ContributorGuidelines)

**Comment by jsichi** [comment]
Awesome.  I've opened up the wiki access here so fire away!

https://github.com/jgrapht/jgrapht/wiki

Then I'll shut down the old sf.net wiki.

**Comment by jsichi** [comment]
Also, please feel free to send me a pull request for adding yourself to the credits...it is great to have people helping me modernize everything.

**Comment by jsichi** [comment]
I've moved the website over verbatim to jgrapht.github.com; DNS change should propagate through tomorrow and then we can start pushing new site changes there.

**Comment by oschrenk** [comment]
I recreated the wiki at https://github.com/jgrapht/jgrapht/wiki/_preview.

I'll open a new issue at the jgrapht/jgrapht for further discussion and close this issue.
